model:
  name: distilbert-base-uncased
  max_length: 256
  num_labels: 27
  class_names:
    - event organization
    - other
    - product launching & presentation
    - patent publication
    - investment in public company
    - foundation
    - expanding industry
    - department establishment
    - closing
    - subsidiary establishment
    - executive statement
    - ipo exit
    - service & product providing
    - hiring
    - expanding geography
    - product updates
    - executive appointment
    - m&a
    - new initiatives & programs
    - company description
    - support & philanthropy
    - funding round
    - clinical trial sponsorship
    - alliance & partnership
    - participation in an event
    - regulatory approval
    - article publication


training:
  output_dir: experiments/distilbert_v2
  bert_peft_trainer: experiments/bert_peft_model_v2
  learning_rate: 5e-5
  batch_size: 16
  epochs: 3
  optimizer: adamw_torch
  logging_steps: 10
  evaluation_strategy: epoch
  save_strategy: epoch
  save_total_limit: 5
  load_best_model_at_end: true
  metric_for_best_model: eval_f1_micro


data:
  processed_path: data/processed/eu_dataset_tokenized
  processed_path_debug: data/processed/eu_dataset_tokenized_with_text
  text_column: Text
  label_column: labels
  eval_split: 0.1


lora:
  r: 16
  alpha: 32
  target_modules: ["q_lin", "k_lin", "v_lin", "out_lin"]
  bias: lora_only
  loftq_bits: 4
  lora_dropout: 0.1
  task_type: SEQ_CLS # this is necessary
  inference_mode: true